Twilight: list[str] = ...
IceFire: list[str] = ...
Edge: list[str] = ...
Phase: list[str] = ...
HSV: list[str] = ...
mrybm: list[str] = ...
mygbm: list[str] = ...

Edge_r: list[str] = ...
HSV_r: list[str] = ...
IceFire_r: list[str] = ...
Phase_r: list[str] = ...
Twilight_r: list[str] = ...
mrybm_r: list[str] = ...
mygbm_r: list[str] = ...
