Plotly: list[str] = ...

D3: list[str] = ...
G10: list[str] = ...
T10: list[str] = ...
Alphabet: list[str] = ...
Dark24: list[str] = ...
Light24: list[str] = ...

Alphabet_r: list[str] = ...
D3_r: list[str] = ...
Dark24_r: list[str] = ...
G10_r: list[str] = ...
Light24_r: list[str] = ...
Plotly_r: list[str] = ...
T10_r: list[str] = ...

Set1: list[str] = ...
Pastel1: list[str] = ...
Dark2: list[str] = ...
Set2: list[str] = ...
Pastel2: list[str] = ...
Set3: list[str] = ...
Set1_r: list[str] = ...
Pastel1_r: list[str] = ...
Dark2_r: list[str] = ...
Set2_r: list[str] = ...
Pastel2_r: list[str] = ...
Set3_r: list[str] = ...

Antique: list[str] = ...
Bold: list[str] = ...
Pastel: list[str] = ...
Prism: list[str] = ...
Safe: list[str] = ...
Vivid: list[str] = ...
Antique_r: list[str] = ...
Bold_r: list[str] = ...
Pastel_r: list[str] = ...
Prism_r: list[str] = ...
Safe_r: list[str] = ...
Vivid_r: list[str] = ...
